export type DiscoverySource = {
  id: string;
  name: string;
  authority: "primary" | "official-secondary";
  purpose: string;
  cadence: "hourly" | "daily" | "weekly" | "monthly" | "quarterly" | "annual";
  discoversCompanies: boolean;
  url: string;
  coverageRole?: "required" | "deferred" | "corroborative" | "sensor";
};

export const discoverySources: DiscoverySource[] = [
  {
    id: "sec-edgar",
    name: "SEC EDGAR",
    authority: "primary",
    purpose: "Discover S-1/F-1/8-A/10 registrations, company filings, ticker/exchange metadata and material disclosures.",
    cadence: "hourly",
    discoversCompanies: true,
    url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
  },
  {
    id: "nyse-listings",
    name: "NYSE Listings",
    authority: "primary",
    purpose: "Detect NYSE/NYSE American listings, IPOs, direct listings and transfers.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.nyse.com/listings",
  },
  {
    id: "nasdaq-ipo",
    name: "Nasdaq IPO Calendar",
    authority: "official-secondary",
    purpose: "Track filed, upcoming and priced Nasdaq IPO candidates; confirm with SEC filings before admission.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.nasdaq.com/market-activity/ipos",
  },
  {
    id: "cboe-new-listings",
    name: "Cboe New Listings",
    authority: "primary",
    purpose: "Detect new Cboe-listed operating companies and transfers; filter out ETPs/ETFs.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.cboe.com/us/equities/notices/new_listings/",
  },
  {
    id: "finra-otc-daily-list",
    name: "FINRA OTC Daily List",
    authority: "primary",
    purpose: "Detect OTC additions, deletions, symbol changes and corporate actions before possible uplistings.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://otce.finra.org/otce/dailyList?viewType=Additions",
    coverageRole: "required",
  },
  {
    id: "otc-markets-directory",
    name: "OTC Markets Company Directory",
    authority: "official-secondary",
    purpose: "Maintain corroborative coverage of development-stage and international securities outside major exchanges; FINRA is the primary automated OTC corporate-action feed.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.otcmarkets.com/corporate-services/company-directory",
    coverageRole: "corroborative",
  },
  {
    id: "usaspending",
    name: "USAspending.gov",
    authority: "primary",
    purpose: "Track federal contract and assistance awards that validate demand, backlog and strategic relevance.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.usaspending.gov/",
    coverageRole: "required",
  },
  {
    id: "sam-gov",
    name: "SAM.gov",
    authority: "primary",
    purpose: "Track federal solicitations, award opportunities and newly relevant government suppliers. Deferred until an API key is intentionally configured.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://sam.gov/",
    coverageRole: "deferred",
  },
  {
    id: "federal-register",
    name: "FederalRegister.gov API",
    authority: "official-secondary",
    purpose: "Detect proposed rules, final rules, notices and public-inspection documents that can create regulatory regime shifts before they are reflected in company reporting. Verify legally material conclusions against the official rule or agency source.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.federalregister.gov/developers/api/v1",
    coverageRole: "sensor",
  },
  {
    id: "bis-export-controls",
    name: "Bureau of Industry and Security — EAR / Entity List",
    authority: "primary",
    purpose: "Detect export-control, Entity List, end-use and semiconductor/manufacturing restrictions that can abruptly change technology supply chains, addressable markets and strategic bottlenecks.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.bis.gov/ear/title-15/subtitle-b/chapter-vii/subchapter-c/part-744/ss-74416-entity-list",
    coverageRole: "sensor",
  },
  {
    id: "ofac-sanctions",
    name: "U.S. Treasury OFAC Sanctions List Service",
    authority: "primary",
    purpose: "Detect sanctions additions, removals and program changes that can alter counterparties, shipping, financing, strategic materials and cross-border technology exposure.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://ofac.treasury.gov/sanctions-list-service",
    coverageRole: "sensor",
  },
  {
    id: "nih-reporter",
    name: "NIH RePORTER",
    authority: "primary",
    purpose: "Detect funded biomedical research, organizations, investigators and emerging therapeutic/diagnostic directions before commercial milestones are obvious.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://api.reporter.nih.gov/?urls.primaryName=V2.0",
    coverageRole: "sensor",
  },
  {
    id: "nsf-awards",
    name: "National Science Foundation Awards API",
    authority: "primary",
    purpose: "Detect early funded research, institutions, technical fields and commercialization-adjacent capabilities across compute, quantum, robotics, materials, energy and infrastructure.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://resources.research.gov/common/webapi/awardapisearch-v1.htm",
    coverageRole: "sensor",
  },
  {
    id: "cisa-kev",
    name: "CISA Known Exploited Vulnerabilities Catalog",
    authority: "primary",
    purpose: "Detect real-world exploitation and vendor/product security pressure that can change cyber demand, trust, replacement cycles and operational risk.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
    coverageRole: "sensor",
  },
  {
    id: "nhtsa-data",
    name: "NHTSA Datasets and APIs",
    authority: "primary",
    purpose: "Track safety defects, complaints, recalls and vehicle-safety data relevant to autonomy, EVs, mobility platforms, sensors and automotive suppliers.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://www.nhtsa.gov/nhtsa-datasets-and-apis",
    coverageRole: "sensor",
  },
  {
    id: "faa-commercial-space",
    name: "FAA Commercial Space Transportation",
    authority: "primary",
    purpose: "Track launch/reentry licenses, permits, approvals and commercial-space operating activity that can validate capability, cadence and infrastructure constraints.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://www.faa.gov/space/licenses",
    coverageRole: "sensor",
  },
  {
    id: "epa-echo",
    name: "EPA ECHO Web Services",
    authority: "primary",
    purpose: "Track facility-level environmental compliance and permitting signals that can reveal industrial expansion constraints, water/emissions exposure and operating risk.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://echo.epa.gov/tools/web-services",
    coverageRole: "sensor",
  },
  {
    id: "doj-antitrust",
    name: "U.S. DOJ Antitrust Case Filings",
    authority: "primary",
    purpose: "Detect antitrust litigation, merger intervention and competitive-policy actions that can change market structure, consolidation assumptions and platform power.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://www.justice.gov/atr/antitrust-case-filings",
    coverageRole: "sensor",
  },
  {
    id: "ftc-cases",
    name: "Federal Trade Commission Cases and Proceedings",
    authority: "primary",
    purpose: "Detect competition, privacy, consumer-protection and technology-policy actions affecting business models, acquisitions, data practices and market power.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://www.ftc.gov/legal-library/browse/cases-proceedings",
    coverageRole: "sensor",
  },
  {
    id: "bea-api",
    name: "U.S. Bureau of Economic Analysis API",
    authority: "primary",
    purpose: "Track industry output, input-output dependencies, regional investment and macro demand shifts that can expose regime change and second-order beneficiaries.",
    cadence: "monthly",
    discoversCompanies: false,
    url: "https://apps.bea.gov/api/signup/",
    coverageRole: "sensor",
  },
  {
    id: "uspto-open-data",
    name: "USPTO Open Data",
    authority: "primary",
    purpose: "Detect patent activity, assignees and technology concentration before commercial scale is obvious.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://developer.uspto.gov/",
  },
  {
    id: "usgs-mcs",
    name: "USGS Mineral Commodity Summaries",
    authority: "primary",
    purpose: "Track production, reserves, import reliance, pricing and concentration for strategic materials.",
    cadence: "annual",
    discoversCompanies: false,
    url: "https://www.usgs.gov/centers/national-minerals-information-center/mineral-commodity-summaries",
  },
  {
    id: "iea-critical-minerals",
    name: "IEA Global Critical Minerals Outlook",
    authority: "official-secondary",
    purpose: "Cross-check long-range mineral demand, supply gaps, processing concentration and substitution pathways.",
    cadence: "annual",
    discoversCompanies: false,
    url: "https://www.iea.org/reports/global-critical-minerals-outlook-2026",
  },
  {
    id: "nerc-ltra",
    name: "NERC Long-Term Reliability Assessment",
    authority: "primary",
    purpose: "Track load growth, data-center demand, reserve margins and grid reliability constraints.",
    cadence: "annual",
    discoversCompanies: false,
    url: "https://www.nerc.com/pa/RAPA/ra/Pages/default.aspx",
  },
  {
    id: "eia",
    name: "U.S. Energy Information Administration",
    authority: "primary",
    purpose: "Track generation, electricity demand, fuel supply, uranium and energy market fundamentals.",
    cadence: "monthly",
    discoversCompanies: false,
    url: "https://www.eia.gov/",
  },
  {
    id: "nrc",
    name: "U.S. Nuclear Regulatory Commission",
    authority: "primary",
    purpose: "Track reactor licensing, construction, operating status and regulatory milestones.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://www.nrc.gov/",
  },
  {
    id: "ferc",
    name: "Federal Energy Regulatory Commission",
    authority: "primary",
    purpose: "Track transmission, interconnection, generation and energy-infrastructure approvals.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://www.ferc.gov/",
  },
  {
    id: "doe",
    name: "U.S. Department of Energy",
    authority: "primary",
    purpose: "Track grants, demonstration programs, grid, nuclear, battery, cooling and advanced-energy milestones.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.energy.gov/",
  },
  {
    id: "nist",
    name: "National Institute of Standards and Technology",
    authority: "primary",
    purpose: "Track cybersecurity, identity, post-quantum cryptography, AI and measurement standards.",
    cadence: "weekly",
    discoversCompanies: false,
    url: "https://www.nist.gov/",
  },
  {
    id: "nasa",
    name: "NASA",
    authority: "primary",
    purpose: "Track launch, lunar, science, exploration, SBIR and space-infrastructure milestones and suppliers.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.nasa.gov/",
  },
  {
    id: "clinicaltrials",
    name: "ClinicalTrials.gov",
    authority: "primary",
    purpose: "Track clinical milestones, sponsors and trial progression for health and longevity companies.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://clinicaltrials.gov/",
    coverageRole: "required",
  },
  {
    id: "fda",
    name: "U.S. Food and Drug Administration",
    authority: "primary",
    purpose: "Track approvals, clearances, safety actions and regulatory milestones in biotech and medtech.",
    cadence: "daily",
    discoversCompanies: true,
    url: "https://www.fda.gov/",
    coverageRole: "required",
  },
  {
    id: "fcc",
    name: "Federal Communications Commission",
    authority: "primary",
    purpose: "Track spectrum, satellite, telecom and communications licensing milestones.",
    cadence: "weekly",
    discoversCompanies: true,
    url: "https://www.fcc.gov/",
  },
  {
    id: "bls",
    name: "U.S. Bureau of Labor Statistics",
    authority: "primary",
    purpose: "Track labor shortages, wages, productivity and occupational change that can drive automation demand.",
    cadence: "monthly",
    discoversCompanies: false,
    url: "https://www.bls.gov/",
  },
];

export const companyDiscoverySources = discoverySources.filter((source) => source.discoversCompanies);
export const sensorSources = discoverySources.filter((source) => source.coverageRole === "sensor");
export const gatingDiscoverySources = discoverySources.filter(
  (source) => source.coverageRole !== "deferred" && source.coverageRole !== "corroborative" && source.coverageRole !== "sensor",
);
