export type ExpansionSeed = { ticker: string; company: string; division: string; lane: string };

function seedGroup(division: string, lane: string, members: readonly (readonly [string, string])[]): ExpansionSeed[] {
  return members.map(([ticker, company]) => ({ ticker, company, division, lane }));
}

export const additionalContenderSeeds: ExpansionSeed[] = [
  ...seedGroup("AI Platforms / Software", "AI platforms / enterprise software / agents", [
    ["MSFT", "Microsoft"],
    ["GOOGL", "Alphabet"],
    ["META", "Meta Platforms"],
    ["AMZN", "Amazon"],
    ["AAPL", "Apple"],
    ["IBM", "IBM"],
    ["PLTR", "Palantir Technologies"],
    ["NOW", "ServiceNow"],
    ["SNOW", "Snowflake"],
    ["DDOG", "Datadog"],
    ["MDB", "MongoDB"],
    ["CRM", "Salesforce"],
    ["AI", "C3.ai"],
    ["SOUN", "SoundHound AI"],
    ["PATH", "UiPath"],
  ]),

  ...seedGroup("Semiconductors / Equipment", "Semiconductor manufacturing / design / equipment", [
    ["TSM", "Taiwan Semiconductor Manufacturing"],
    ["ASML", "ASML Holding"],
    ["AMAT", "Applied Materials"],
    ["LRCX", "Lam Research"],
    ["KLAC", "KLA"],
    ["QCOM", "Qualcomm"],
    ["TXN", "Texas Instruments"],
    ["ADI", "Analog Devices"],
    ["NXPI", "NXP Semiconductors"],
    ["MCHP", "Microchip Technology"],
    ["ON", "onsemi"],
    ["STM", "STMicroelectronics"],
    ["GFS", "GlobalFoundries"],
    ["INTC", "Intel"],
    ["QRVO", "Qorvo"],
    ["ACLS", "Axcelis Technologies"],
    ["MKSI", "MKS Instruments"],
    ["ENTG", "Entegris"],
    ["FORM", "FormFactor"],
    ["CAMT", "Camtek"],
  ]),

  ...seedGroup("Compute Hardware / Photonics", "Networking / photonics / compute hardware", [
    ["CSCO", "Cisco Systems"],
    ["CIEN", "Ciena"],
    ["FN", "Fabrinet"],
    ["AAOI", "Applied Optoelectronics"],
    ["GLW", "Corning"],
    ["KEYS", "Keysight Technologies"],
    ["VIAV", "Viavi Solutions"],
    ["JBL", "Jabil"],
    ["FLEX", "Flex"],
    ["SANM", "Sanmina"],
  ]),

  ...seedGroup("Digital Infrastructure", "Data centers / towers / powered digital infrastructure", [
    ["EQIX", "Equinix"],
    ["DLR", "Digital Realty"],
    ["AMT", "American Tower"],
    ["CCI", "Crown Castle"],
    ["CORZ", "Core Scientific"],
    ["CIFR", "Cipher Mining"],
  ]),

  ...seedGroup("Power / Grid / Utilities", "Electricity generation / grid / electrical infrastructure", [
    ["HUBB", "Hubbell"],
    ["EMR", "Emerson Electric"],
    ["NVT", "nVent Electric"],
    ["GNRC", "Generac"],
    ["MYRG", "MYR Group"],
    ["EME", "EMCOR Group"],
    ["FIX", "Comfort Systems USA"],
    ["MTZ", "MasTec"],
    ["AEP", "American Electric Power"],
    ["NEE", "NextEra Energy"],
    ["SO", "Southern Company"],
    ["DUK", "Duke Energy"],
    ["EXC", "Exelon"],
    ["XEL", "Xcel Energy"],
    ["PEG", "Public Service Enterprise Group"],
    ["PCG", "PG&E"],
  ]),

  ...seedGroup("Nuclear / Fuel", "Nuclear fuel / services / reactor supply chain", [
    ["LEU", "Centrus Energy"],
    ["UEC", "Uranium Energy"],
    ["UUUU", "Energy Fuels"],
    ["NXE", "NexGen Energy"],
    ["DNN", "Denison Mines"],
    ["BWXT", "BWX Technologies"],
  ]),

  ...seedGroup("Strategic Materials / Processing", "Critical minerals / metals / processing", [
    ["FCX", "Freeport-McMoRan"],
    ["SCCO", "Southern Copper"],
    ["TECK", "Teck Resources"],
    ["RIO", "Rio Tinto"],
    ["BHP", "BHP Group"],
    ["VALE", "Vale"],
    ["MP", "MP Materials"],
    ["LAC", "Lithium Americas"],
    ["ALB", "Albemarle"],
    ["SQM", "Sociedad Química y Minera de Chile"],
    ["NTR", "Nutrien"],
    ["MOS", "Mosaic"],
    ["ATI", "ATI"],
    ["CRS", "Carpenter Technology"],
    ["AA", "Alcoa"],
    ["CENX", "Century Aluminum"],
    ["CSTM", "Constellium"],
    ["NUE", "Nucor"],
    ["STLD", "Steel Dynamics"],
    ["CLF", "Cleveland-Cliffs"],
  ]),

  ...seedGroup("Energy Storage / Clean Power", "Storage / solar / distributed clean power", [
    ["TSLA", "Tesla"],
    ["QS", "QuantumScape"],
    ["SLDP", "Solid Power"],
    ["ENVX", "Enovix"],
    ["MVST", "Microvast"],
    ["FLNC", "Fluence Energy"],
    ["EOSE", "Eos Energy Enterprises"],
    ["STEM", "Stem"],
    ["ENPH", "Enphase Energy"],
    ["SEDG", "SolarEdge Technologies"],
    ["FSLR", "First Solar"],
    ["NXT", "Nextracker"],
    ["ARRY", "Array Technologies"],
    ["SHLS", "Shoals Technologies Group"],
    ["PLUG", "Plug Power"],
  ]),

  ...seedGroup("Robotics / Autonomy / Mobility", "Robotics / autonomy / machine vision / mobility", [
    ["ISRG", "Intuitive Surgical"],
    ["CGNX", "Cognex"],
    ["ZBRA", "Zebra Technologies"],
    ["HON", "Honeywell"],
    ["DE", "Deere & Company"],
    ["CAT", "Caterpillar"],
    ["PCAR", "PACCAR"],
    ["OUST", "Ouster"],
    ["ACHR", "Archer Aviation"],
    ["AEVA", "Aeva Technologies"],
    ["INVZ", "Innoviz Technologies"],
    ["JOBY", "Joby Aviation"],
  ]),

  ...seedGroup("Space / Defense", "Defense / aerospace / mission systems", [
    ["LMT", "Lockheed Martin"],
    ["NOC", "Northrop Grumman"],
    ["RTX", "RTX"],
    ["GD", "General Dynamics"],
    ["BA", "Boeing"],
    ["LHX", "L3Harris Technologies"],
    ["HII", "Huntington Ingalls Industries"],
    ["TXT", "Textron"],
    ["MRCY", "Mercury Systems"],
    ["CW", "Curtiss-Wright"],
    ["TDG", "TransDigm Group"],
    ["HEI", "HEICO"],
  ]),

  ...seedGroup("Cyber / Identity / Trust", "Cybersecurity / identity / digital trust", [
    ["PANW", "Palo Alto Networks"],
    ["CRWD", "CrowdStrike"],
    ["FTNT", "Fortinet"],
    ["ZS", "Zscaler"],
    ["OKTA", "Okta"],
    ["SAIL", "SailPoint"],
    ["TENB", "Tenable"],
    ["RPD", "Rapid7"],
    ["S", "SentinelOne"],
    ["NET", "Cloudflare"],
    ["CHKP", "Check Point Software"],
    ["QLYS", "Qualys"],
    ["GEN", "Gen Digital"],
    ["VRNS", "Varonis Systems"],
    ["RBRK", "Rubrik"],
  ]),

  ...seedGroup("Water / Thermal / Resilience", "Water / cooling / thermal / resilience infrastructure", [
    ["XYL", "Xylem"],
    ["WTS", "Watts Water Technologies"],
    ["PNR", "Pentair"],
    ["ECL", "Ecolab"],
    ["AWK", "American Water Works"],
    ["WTRG", "Essential Utilities"],
    ["MWA", "Mueller Water Products"],
    ["BMI", "Badger Meter"],
    ["CWCO", "Consolidated Water"],
    ["ERII", "Energy Recovery"],
  ]),

  ...seedGroup("Biotech / Health / Longevity", "Biotech / precision health / longevity", [
    ["LLY", "Eli Lilly"],
    ["NVO", "Novo Nordisk"],
    ["REGN", "Regeneron Pharmaceuticals"],
    ["VRTX", "Vertex Pharmaceuticals"],
    ["CRSP", "CRISPR Therapeutics"],
    ["NTLA", "Intellia Therapeutics"],
    ["BEAM", "Beam Therapeutics"],
    ["EDIT", "Editas Medicine"],
    ["RXRX", "Recursion Pharmaceuticals"],
    ["SDGR", "Schrödinger"],
  ]),

  ...seedGroup("Communications / Connectivity", "Telecom / connectivity / communications infrastructure", [
    ["TMUS", "T-Mobile US"],
    ["VZ", "Verizon Communications"],
    ["T", "AT&T"],
    ["NOK", "Nokia"],
    ["ERIC", "Ericsson"],
  ]),

  ...seedGroup("Advanced Manufacturing / Industrial", "Advanced manufacturing / industrial systems", [
    ["PH", "Parker-Hannifin"],
    ["GE", "GE Aerospace"],
    ["ITW", "Illinois Tool Works"],
    ["CMI", "Cummins"],
    ["DOV", "Dover"],
    ["ROP", "Roper Technologies"],
    ["IR", "Ingersoll Rand"],
    ["AME", "AMETEK"],
    ["AOS", "A. O. Smith"],
  ]),

  ...seedGroup("Agriculture / Bio Systems", "Agriculture / fertilizer / biological productivity", [
    ["CTVA", "Corteva"],
    ["ADM", "Archer-Daniels-Midland"],
    ["BG", "Bunge Global"],
    ["CF", "CF Industries"],
    ["FMC", "FMC"],
  ]),

  ...seedGroup("Financial / Digital Infrastructure", "Payments / digital assets / financial rails", [
    ["V", "Visa"],
    ["MA", "Mastercard"],
    ["COIN", "Coinbase"],
    ["PYPL", "PayPal"],
  ]),

  ...seedGroup("Energy / Gas Infrastructure", "Gas / LNG / dispatchable energy infrastructure", [
    ["LNG", "Cheniere Energy"],
    ["EQT", "EQT"],
    ["DVN", "Devon Energy"],
    ["WMB", "Williams Companies"],
    ["KMI", "Kinder Morgan"],
  ]),

  ...seedGroup("Human Platforms / Experience", "Attention / travel / entertainment / human experience", [
    ["RDDT", "Reddit"],
    ["SPOT", "Spotify Technology"],
    ["NFLX", "Netflix"],
    ["ABNB", "Airbnb"],
    ["BKNG", "Booking Holdings"],
  ]),
];

export const ADDITIONAL_SEED_COUNT = additionalContenderSeeds.length;
